### ISSUE TITLE
Bulma logo size when setting theme_variant

### ISSUE THREAD

**Issue by gquintana** [jeblister/bulma#11]
As soon as I change the theme_variant, I get something ugly:
![image](https://user-images.githubusercontent.com/755587/39706125-afa81302-5210-11e8-890d-223090b59c91.png)
The Bulma logo is oversized

**Comment by gquintana** [comment]
In bulmaswatch.min.css, there is 
```css
img {
    height: auto;
}
In comparison, in bulma.css there is: 
```
.nav-item img {

    max-height: 1.75rem;

}
But when theme_variant is set this file is not loaded anymore
